let stopFoodDays=null,stopFoodProfile=null;
let foodDays=[],foodProfile=null,currentFoodDate='';
const qc=(s,r=document)=>r.querySelector(s),qca=(s,r=document)=>[...r.querySelectorAll(s)];
const isoC=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const escC=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt1=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:1}).format(Number(n||0));
function sayC(m){try{window.eval(`if(typeof say==='function')say(${JSON.stringify(m)})`)}catch{console.log(m)}}
function dateObj(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function shiftDate(s,n){const d=dateObj(s);d.setDate(d.getDate()+n);return isoC(d)}
function dayLabel(s){const d=dateObj(s),today=isoC();if(s===today)return 'Hoy';if(s===shiftDate(today,-1))return 'Ayer';return d.toLocaleDateString('es-AR',{weekday:'short',day:'numeric',month:'short'}).replace('.','')}
function currentDay(){return foodDays.find(x=>x.date===currentFoodDate)||{date:currentFoodDate,foods:[],supplements:[],exercise:[],weightKg:null}}
function cloneDay(){const d=currentDay();return JSON.parse(JSON.stringify(d))}
function saveDay(d){return window.PirulinComidas.saveDay(d)}
function totals(d=currentDay()){return window.PirulinComidas.totals(d)}

function installComidas(){
  const suite=qc('#comidasSuite');if(!suite||suite.dataset.live==='1')return !!suite;
  suite.dataset.live='1';
  suite.innerHTML=`<div id="comidasApp" class="comidas-app">
    <div class="comidas-head"><button class="header-back" id="backFromComidas" type="button">‹</button><div class="comidas-logo-wrap"><span>🍽️</span></div><h1>Comidas</h1><div class="header-spacer"></div><button class="icon-btn" id="comidasMore">•••</button></div>
    <div class="comidas-datebar"><button id="foodPrev">‹</button><label><strong id="foodDayLabel">Hoy</strong><input id="foodDate" type="date"></label><button id="foodNext">›</button></div>
    <div id="comidasScroll" class="comidas-scroll"><div id="comidasBody"></div></div>
    <button id="foodPasteFab" class="food-paste-fab" type="button">Pegar registro</button>
  </div>
  <div id="comidasMenu" class="comidas-pop"><button data-cm="paste">Pegar registro JSON</button><button data-cm="profile">Perfil y objetivos</button><button data-cm="history">Historial</button><button data-cm="export">Exportar datos</button></div>
  <div id="foodModal" class="comidas-modal"><div class="comidas-sheet"><h2 id="foodModalTitle">Editar</h2><div id="foodModalBody"></div><div class="comidas-actions"><button data-close="foodModal">Cancelar</button><button class="primary" id="foodModalSave">Guardar</button></div></div></div>
  <div id="foodPasteModal" class="comidas-modal"><div class="comidas-sheet paste-sheet"><h2>Pegar registro</h2><p>Pegá el JSON ya curado por ChatGPT. Pirulín no va a estimar nada.</p><textarea id="foodPasteText" spellcheck="false" placeholder='{"date":"2026-08-22","foods":[...]}'></textarea><div class="comidas-actions"><button data-close="foodPasteModal">Cancelar</button><button class="primary" id="foodPasteSave">Importar</button></div></div></div>
  <div id="foodProfileModal" class="comidas-modal"><div class="comidas-sheet profile-sheet"><h2>Perfil y objetivos</h2><div id="foodProfileForm"></div><div class="comidas-actions"><button data-close="foodProfileModal">Cancelar</button><button class="primary" id="foodProfileSave">Guardar</button></div></div></div>
  <div id="foodHistoryModal" class="comidas-modal"><div class="comidas-sheet history-sheet"><div class="history-head"><h2>Historial</h2><button data-close="foodHistoryModal">×</button></div><div id="foodHistoryBody"></div></div></div>`;
  const style=document.createElement('style');style.id='comidasLiveStyle';style.textContent=`
    #comidasSuite{height:100%;display:none;background:#fbfbfc}#comidasSuite.show{display:block}#comidasApp{height:100%;display:flex;flex-direction:column;padding:8px 18px 0}
    .comidas-head{display:flex;align-items:center;gap:12px;padding:2px 2px 10px}.comidas-head h1{font-size:27px;margin:0}.comidas-logo-wrap{width:44px;height:44px;border-radius:14px;background:#fff2dc;display:grid;place-items:center;font-size:25px;box-shadow:0 7px 18px rgba(45,39,25,.06)}
    .comidas-datebar{height:48px;display:grid;grid-template-columns:42px 1fr 42px;align-items:center;background:#fff;border:1px solid #eceff4;border-radius:18px;box-shadow:0 7px 20px rgba(29,42,77,.045);margin-bottom:10px}.comidas-datebar button{border:0;background:transparent;font-size:25px;color:#687185}.comidas-datebar label{text-align:center;position:relative}.comidas-datebar strong{font-size:14px}.comidas-datebar input{position:absolute;inset:0;opacity:0;width:100%}
    .comidas-scroll{flex:1;overflow:auto;padding-bottom:110px;scrollbar-width:none}.comidas-scroll::-webkit-scrollbar{display:none}.food-summary{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin:4px 0 10px}.food-stat{background:#fff;border:1px solid #eceff4;border-radius:18px;padding:12px 8px;text-align:center}.food-stat b{display:block;font-size:20px;color:#303641}.food-stat span{font-size:9.5px;color:#89909c;font-weight:900;text-transform:uppercase;letter-spacing:.06em}
    .food-scale-card,.food-section,.food-reco{background:#fff;border:1px solid #eceff4;border-radius:20px;padding:14px;margin:9px 0;box-shadow:0 7px 20px rgba(29,42,77,.035)}.food-scale-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:9px}.food-scale-head b{font-size:14px}.food-scale-head span{font-size:11px;color:#858c98;font-weight:800}.food-scale{height:11px;display:grid;grid-template-columns:repeat(5,1fr);gap:2px;position:relative;margin:19px 0 7px}.food-scale i{display:block;border-radius:4px}.food-scale i:nth-child(1){background:#f2b4a7}.food-scale i:nth-child(2){background:#f3d597}.food-scale i:nth-child(3){background:#91d6ae}.food-scale i:nth-child(4){background:#8ec9d8}.food-scale i:nth-child(5){background:#cab5dc}.food-marker{position:absolute;top:-9px;width:3px;height:29px;background:#303641;border-radius:3px;transform:translateX(-50%);transition:left .35s cubic-bezier(.2,.9,.2,1)}.food-marker:before{content:'';position:absolute;left:50%;top:-3px;width:8px;height:8px;border-radius:50%;background:#303641;transform:translateX(-50%)}.food-scale-labels{display:grid;grid-template-columns:repeat(5,1fr);gap:2px;text-align:center;font-size:8px;color:#9299a5;font-weight:800;line-height:1.05}
    .food-reco{padding:12px 14px;font-weight:900;font-size:13px;background:#f8f7ff;border-color:#ece7fa}.food-section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.food-section-head h3{margin:0;font-size:16px}.food-add{border:0;background:#f1f3f7;color:#586172;border-radius:11px;padding:7px 10px;font-size:11px;font-weight:900}.food-table{width:100%;border-collapse:collapse}.food-table th,.food-table td{padding:8px 3px;border-bottom:1px solid #f0f1f4;font-size:11px;text-align:right}.food-table th:first-child,.food-table td:first-child{text-align:left}.food-table th{color:#9298a3;font-size:9px;text-transform:uppercase}.food-table td:first-child button{border:0;background:transparent;padding:0;color:#343a45;text-align:left;font-weight:800}.food-total td{font-weight:900;border-bottom:0}.food-empty{color:#999faa;font-size:12px;padding:7px 0}.food-chip-list{display:flex;flex-wrap:wrap;gap:7px}.food-chip{border:0;border-radius:999px;padding:7px 10px;background:#f3f5f8;font-size:10.5px;font-weight:800;color:#515966}.exercise-row{display:flex;align-items:center;gap:9px;padding:8px 0;border-bottom:1px solid #f0f1f4}.exercise-row:last-child{border-bottom:0}.exercise-icon{width:34px;height:34px;border-radius:11px;background:#eaf6f1;display:grid;place-items:center}.exercise-copy{flex:1;min-width:0}.exercise-copy b{font-size:12px}.exercise-copy small{display:block;color:#9097a2;font-size:10px}.exercise-row button{border:0;background:transparent;color:#7c8490}.weight-row{display:flex;justify-content:space-between;align-items:center}.weight-row b{font-size:22px}.weight-row small{color:#9299a5}
    .food-paste-fab{position:absolute;right:18px;bottom:20px;z-index:25;border:0;border-radius:17px;padding:13px 16px;background:linear-gradient(145deg,#ff7b62,#ff5e5b);color:#fff;font-size:12px;font-weight:900;box-shadow:0 14px 28px rgba(255,94,91,.24)}
    .comidas-pop{display:none;position:fixed;z-index:140;width:205px;background:#fff;border:1px solid #e7eaf0;border-radius:16px;padding:6px;box-shadow:0 16px 40px rgba(25,30,40,.18)}.comidas-pop.show{display:block}.comidas-pop button{display:block;width:100%;border:0;background:transparent;padding:10px 11px;border-radius:10px;text-align:left;font-size:12px;font-weight:800;color:#353b46}.comidas-pop button:active{background:#f2f4f7}
    .comidas-modal{position:absolute;inset:0;z-index:150;display:none;align-items:flex-end;background:rgba(20,26,40,.22);backdrop-filter:blur(3px)}.comidas-modal.show{display:flex;animation:cmBack .15s ease both}.comidas-sheet{width:100%;background:#fff;border-radius:26px 26px 0 0;padding:18px 18px calc(22px + env(safe-area-inset-bottom));max-height:90%;overflow:auto;animation:cmSheet .2s cubic-bezier(.2,.9,.2,1) both}.comidas-sheet h2{margin:0 0 12px;font-size:21px}.comidas-sheet p{font-size:11px;color:#7f8793}.cm-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.cm-field{display:grid;gap:5px;margin:8px 0}.cm-field.full{grid-column:1/-1}.cm-field label{font-size:10px;font-weight:900;color:#818996}.cm-field input,.cm-field select,.comidas-sheet textarea{width:100%;border:1px solid #e1e5ec;border-radius:13px;background:#fbfcfe;padding:11px 12px;outline:none;color:#343a45;font-weight:700}.comidas-sheet textarea{height:220px;resize:none;font:12px/1.4 ui-monospace,monospace}.comidas-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}.comidas-actions button,.history-head button{border:0;border-radius:13px;padding:11px;background:#f0f2f6;font-weight:900;color:#505866}.comidas-actions .primary{background:linear-gradient(145deg,#ff7b62,#ff5e5b);color:#fff}.history-sheet{height:92%;display:flex;flex-direction:column}.history-head{display:flex;align-items:center;justify-content:space-between}.history-head h2{margin:0}.history-head button{width:36px;height:36px;padding:0}.history-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.history-summary div{background:#f5f6f9;border-radius:14px;padding:9px;text-align:center}.history-summary b{display:block;font-size:15px}.history-summary span{font-size:8.5px;color:#9096a0;font-weight:900}.history-list{overflow:auto}.history-day{display:grid;grid-template-columns:70px 1fr auto;gap:8px;align-items:center;padding:11px 4px;border-bottom:1px solid #eff1f4}.history-day button{border:0;background:transparent;text-align:left;font-weight:900;color:#353b46}.history-day small{color:#8d949f}.history-day b{font-size:12px}
    @keyframes cmBack{from{opacity:0}to{opacity:1}}@keyframes cmSheet{from{transform:translateY(18px);opacity:.5}to{transform:none;opacity:1}}
  `;document.head.appendChild(style);
  wireComidas();return true;
}
function profileTargets(){const p=foodProfile||window.PirulinComidas.DEFAULT_PROFILE;const sug=window.PirulinComidas.suggestedCalories(p);return {low:p.autoCalories?sug.low:p.calorieTargetLow,high:p.autoCalories?sug.high:p.calorieTargetHigh,maintenance:sug.maintenance||Math.round(p.calorieTargetHigh*1.22),pLow:p.proteinTargetLow,pHigh:p.proteinTargetHigh}}
function markerPct(value,bounds){const [a,b,c,d]=bounds;let pct;if(value<=a)pct=20*(value/Math.max(a,1));else if(value<=b)pct=20+20*(value-a)/Math.max(b-a,1);else if(value<=c)pct=40+20*(value-b)/Math.max(c-b,1);else if(value<=d)pct=60+20*(value-c)/Math.max(d-c,1);else pct=80+20*Math.min(1,(value-d)/Math.max(d*.35,1));return Math.max(1,Math.min(99,pct))}
function calorieStatus(k,t){if(k<t.low*.72)return 'Muy bajo';if(k<t.low)return 'Bajo';if(k<=t.high)return 'Objetivo';if(k<=t.maintenance*1.05)return 'Mantenimiento';return 'Alto'}
function proteinStatus(v,t){if(v<t.pLow*.65)return 'Baja';if(v<t.pLow)return 'Mejorable';if(v<t.pHigh*.92)return 'Buena';if(v<=t.pHigh*1.08)return 'Óptima';return 'Alta'}
function recommendation(d,t,tot){if(tot.kcal<t.low*.72)return 'Aumentar ligeramente la ingesta.';if(tot.protein<t.pLow)return 'Consumir más proteína.';if(tot.kcal>t.maintenance*1.05)return 'Reducir calorías.';if(tot.kcal>=t.low&&tot.kcal<=t.high&&tot.protein>=t.pLow)return '¡Excelente día!';const recent=foodDays.filter(x=>x.date<currentFoodDate).slice(0,3);if(!tot.exerciseMin&&recent.length>=3&&recent.every(x=>!window.PirulinComidas.totals(x).exerciseMin))return 'Sumar actividad física.';return 'Seguir registrando: la tendencia importa más que un día.'}
function scaleHTML(title,value,unit,labels,pct,status){return `<div class="food-scale-card"><div class="food-scale-head"><b>${title}</b><span>${fmt1(value)} ${unit} · ${status}</span></div><div class="food-scale"><i></i><i></i><i></i><i></i><i></i><span class="food-marker" style="left:${pct}%"></span></div><div class="food-scale-labels">${labels.map(x=>`<span>${x}</span>`).join('')}</div></div>`}
function renderComidas(){const body=qc('#comidasBody');if(!body)return;const d=currentDay(),tot=totals(d),t=profileTargets();qc('#foodDate').value=currentFoodDate;qc('#foodDayLabel').textContent=dayLabel(currentFoodDate);const cPct=markerPct(tot.kcal,[t.low*.72,t.low,t.high,t.maintenance*1.05]);const pPct=markerPct(tot.protein,[t.pLow*.65,t.pLow,t.pHigh*.92,t.pHigh*1.08]);body.innerHTML=`
  <div class="food-summary"><div class="food-stat"><b>${tot.kcal}</b><span>kcal</span></div><div class="food-stat"><b>${fmt1(tot.protein)} g</b><span>proteína</span></div><div class="food-stat"><b>${tot.exerciseMin||'—'}</b><span>${tot.exerciseMin?'min actividad':'sin actividad'}</span></div></div>
  ${scaleHTML('Calorías',tot.kcal,'kcal',['Muy bajo','Bajo','Objetivo','Mantenimiento','Alto'],cPct,calorieStatus(tot.kcal,t))}
  ${scaleHTML('Proteína',tot.protein,'g',['Baja','Mejorable','Buena','Óptima','Alta'],pPct,proteinStatus(tot.protein,t))}
  <div class="food-reco">${recommendation(d,t,tot)}</div>
  <section class="food-section"><div class="food-section-head"><h3>Comidas</h3><button class="food-add" data-add="food">+ Agregar</button></div>${foodTable(d)}</section>
  <section class="food-section"><div class="food-section-head"><h3>Suplementos</h3><button class="food-add" data-add="supplement">+ Agregar</button></div>${supplementsHTML(d)}</section>
  <section class="food-section"><div class="food-section-head"><h3>Actividad física</h3><button class="food-add" data-add="exercise">+ Agregar</button></div>${exerciseHTML(d)}</section>
  <section class="food-section"><div class="food-section-head"><h3>Peso</h3><button class="food-add" data-add="weight">${d.weightKg?'Editar':'+ Registrar'}</button></div><div class="weight-row">${d.weightKg?`<b>${fmt1(d.weightKg)} kg</b><small>Registro del día</small>`:'<span class="food-empty">Sin peso registrado.</span>'}</div></section>`}
function foodTable(d){if(!d.foods?.length)return '<div class="food-empty">Todavía no cargaste comidas.</div>';const rows=d.foods.map(x=>`<tr><td><button data-edit-food="${escC(x.id)}">${escC(x.name)}${x.amount?`<small style="display:block;color:#9aa0aa">${escC(x.amount)}</small>`:''}</button></td><td>${fmt1(x.kcal)}</td><td>${fmt1(x.protein)} g</td></tr>`).join(''),t=totals(d);return `<table class="food-table"><thead><tr><th>Comida</th><th>kcal</th><th>proteína</th></tr></thead><tbody>${rows}<tr class="food-total"><td>Total</td><td>${t.kcal}</td><td>${fmt1(t.protein)} g</td></tr></tbody></table>`}
function supplementsHTML(d){return d.supplements?.length?`<div class="food-chip-list">${d.supplements.map(x=>`<button class="food-chip" data-edit-supp="${escC(x.id)}">${escC(x.name)}${x.amount?' · '+escC(x.amount):''}</button>`).join('')}</div>`:'<div class="food-empty">Sin suplementos registrados.</div>'}
function exerciseHTML(d){return d.exercise?.length?d.exercise.map(x=>`<div class="exercise-row"><div class="exercise-icon">${x.type==='walking'?'🚶':x.type==='gym'?'🏋️':'⚡'}</div><div class="exercise-copy"><b>${escC(x.name)}</b><small>${x.durationMin?`${x.durationMin} min`:''}${x.routine?`${x.durationMin?' · ':''}${escC(x.routine)}`:''}</small></div><button data-edit-ex="${escC(x.id)}">•••</button></div>`).join(''):'<div class="food-empty">Sin actividad registrada.</div>'}
function openModal(type,item=null){const modal=qc('#foodModal'),title=qc('#foodModalTitle'),box=qc('#foodModalBody');modal.dataset.type=type;modal.dataset.id=item?.id||'';if(type==='food'){title.textContent=item?'Editar comida':'Agregar comida';box.innerHTML=`<div class="cm-grid"><div class="cm-field full"><label>Nombre</label><input id="cmName" value="${escC(item?.name||'')}"></div><div class="cm-field"><label>Calorías</label><input id="cmKcal" type="number" min="0" value="${item?.kcal??''}"></div><div class="cm-field"><label>Proteína (g)</label><input id="cmProtein" type="number" min="0" step="0.1" value="${item?.protein??''}"></div><div class="cm-field full"><label>Porción / cantidad (opcional)</label><input id="cmAmount" value="${escC(item?.amount||'')}"></div></div>`}else if(type==='supplement'){title.textContent=item?'Editar suplemento':'Agregar suplemento';box.innerHTML=`<div class="cm-field"><label>Suplemento</label><input id="cmName" value="${escC(item?.name||'')}"></div><div class="cm-field"><label>Cantidad</label><input id="cmAmount" value="${escC(item?.amount||'')}"></div>`}else if(type==='exercise'){title.textContent=item?'Editar actividad':'Agregar actividad';box.innerHTML=`<div class="cm-grid"><div class="cm-field"><label>Tipo</label><select id="cmType"><option value="gym">Gimnasio</option><option value="walking">Caminata</option><option value="other">Otra</option></select></div><div class="cm-field"><label>Duración (min)</label><input id="cmDuration" type="number" min="0" value="${item?.durationMin??''}"></div><div class="cm-field full"><label>Nombre</label><input id="cmName" value="${escC(item?.name||'')}"></div><div class="cm-field full"><label>Rutina (opcional)</label><input id="cmRoutine" value="${escC(item?.routine||'')}"></div></div>`;setTimeout(()=>qc('#cmType').value=item?.type||'gym')}else{title.textContent='Peso del día';box.innerHTML=`<div class="cm-field"><label>Peso (kg)</label><input id="cmWeight" type="number" min="0" step="0.1" value="${currentDay().weightKg??foodProfile?.weightKg??''}"></div>`}modal.classList.add('show');setTimeout(()=>qc('#cmName,#cmWeight')?.focus(),30)}
async function saveModal(){const modal=qc('#foodModal'),type=modal.dataset.type,id=modal.dataset.id,d=cloneDay();if(type==='food'){const name=qc('#cmName').value.trim(),kcal=Number(qc('#cmKcal').value),protein=Number(qc('#cmProtein').value);if(!name||!Number.isFinite(kcal)||!Number.isFinite(protein))return sayC('Completá nombre, calorías y proteína');const x={id:id||`f-${Date.now()}`,name,kcal,protein,amount:qc('#cmAmount').value.trim()};const i=d.foods.findIndex(y=>y.id===id);i>=0?d.foods.splice(i,1,x):d.foods.push(x)}else if(type==='supplement'){const x={id:id||`s-${Date.now()}`,name:qc('#cmName').value.trim(),amount:qc('#cmAmount').value.trim()};if(!x.name)return sayC('Completá el suplemento');const i=d.supplements.findIndex(y=>y.id===id);i>=0?d.supplements.splice(i,1,x):d.supplements.push(x)}else if(type==='exercise'){const x={id:id||`e-${Date.now()}`,type:qc('#cmType').value,name:qc('#cmName').value.trim()||'Actividad',durationMin:Number(qc('#cmDuration').value)||0,routine:qc('#cmRoutine').value.trim()};const i=d.exercise.findIndex(y=>y.id===id);i>=0?d.exercise.splice(i,1,x):d.exercise.push(x)}else{d.weightKg=Number(qc('#cmWeight').value)||null}await saveDay(d);modal.classList.remove('show');sayC('Registro guardado')}
function openProfile(){const p=foodProfile||window.PirulinComidas.DEFAULT_PROFILE,sug=window.PirulinComidas.suggestedCalories(p);qc('#foodProfileForm').innerHTML=`<div class="cm-grid"><div class="cm-field"><label>Peso (kg)</label><input id="pfWeight" type="number" step="0.1" value="${p.weightKg}"></div><div class="cm-field"><label>Altura (cm)</label><input id="pfHeight" type="number" value="${p.heightCm}"></div><div class="cm-field"><label>Edad</label><input id="pfAge" type="number" value="${p.age}"></div><div class="cm-field"><label>Sexo (para cálculo)</label><select id="pfSex"><option value="">Sin definir</option><option value="male">Masculino</option><option value="female">Femenino</option></select></div><div class="cm-field"><label>Actividad</label><select id="pfActivity"><option value="sedentary">Sedentaria</option><option value="light">Ligera</option><option value="moderate">Moderada</option><option value="high">Alta</option></select></div><div class="cm-field"><label>Objetivo</label><select id="pfGoal"><option value="lose">Bajar grasa</option><option value="maintain">Mantener</option><option value="gain">Ganar</option></select></div><div class="cm-field full"><label><input id="pfAuto" type="checkbox" ${p.autoCalories?'checked':''}> Calcular automáticamente rango calórico desde el perfil</label></div><div class="cm-field"><label>Calorías mín.</label><input id="pfCalLow" type="number" value="${p.calorieTargetLow}"></div><div class="cm-field"><label>Calorías máx.</label><input id="pfCalHigh" type="number" value="${p.calorieTargetHigh}"></div><div class="cm-field"><label>Proteína mín. (g)</label><input id="pfProLow" type="number" value="${p.proteinTargetLow}"></div><div class="cm-field"><label>Proteína óptima (g)</label><input id="pfProHigh" type="number" value="${p.proteinTargetHigh}"></div>${sug.maintenance?`<div class="cm-field full"><label>Referencia calculada</label><div style="font-size:12px;color:#727b88">Mantenimiento estimado: <b>${sug.maintenance} kcal</b> · rango sugerido: <b>${sug.low}–${sug.high}</b></div></div>`:''}</div>`;qc('#pfSex').value=p.sex||'';qc('#pfActivity').value=p.activity;qc('#pfGoal').value=p.goal;qc('#foodProfileModal').classList.add('show')}
async function saveProfile(){const p={weightKg:Number(qc('#pfWeight').value),heightCm:Number(qc('#pfHeight').value),age:Number(qc('#pfAge').value),sex:qc('#pfSex').value,activity:qc('#pfActivity').value,goal:qc('#pfGoal').value,autoCalories:qc('#pfAuto').checked,calorieTargetLow:Number(qc('#pfCalLow').value),calorieTargetHigh:Number(qc('#pfCalHigh').value),proteinTargetLow:Number(qc('#pfProLow').value),proteinTargetHigh:Number(qc('#pfProHigh').value)};await window.PirulinComidas.saveProfile(p);qc('#foodProfileModal').classList.remove('show');sayC('Perfil actualizado')}
async function importPaste(){try{const raw=JSON.parse(qc('#foodPasteText').value),incoming=window.PirulinComidas.normalizeDay(raw),existing=foodDays.find(x=>x.date===incoming.date);const merged=existing?{...existing,foods:[...(existing.foods||[]),...incoming.foods],supplements:[...(existing.supplements||[]),...incoming.supplements],exercise:[...(existing.exercise||[]),...incoming.exercise],weightKg:incoming.weightKg??existing.weightKg}:incoming;await saveDay(merged);currentFoodDate=incoming.date;qc('#foodPasteModal').classList.remove('show');qc('#foodPasteText').value='';renderComidas();sayC('Registro importado')}catch(e){console.error(e);sayC('El JSON no es válido')}}
function history(){const box=qc('#foodHistoryBody');const rows=foodDays.slice(0,60),last7=foodDays.filter(x=>x.date>=shiftDate(isoC(),-6)&&x.date<=isoC()),avg=k=>last7.length?Math.round(last7.reduce((s,d)=>s+window.PirulinComidas.totals(d)[k],0)/last7.length):0;box.innerHTML=`<div class="history-summary"><div><b>${avg('kcal')}</b><span>kcal prom. 7d</span></div><div><b>${avg('protein')} g</b><span>proteína prom.</span></div><div><b>${last7.filter(x=>window.PirulinComidas.totals(x).exerciseMin>0).length}</b><span>días activos</span></div></div><div class="history-list">${rows.length?rows.map(d=>{const t=window.PirulinComidas.totals(d);return `<div class="history-day"><button data-history-date="${d.date}">${dayLabel(d.date)}</button><small>${t.kcal} kcal · ${fmt1(t.protein)} g proteína</small><b>${d.weightKg?fmt1(d.weightKg)+' kg':''}</b></div>`}).join(''):'<div class="food-empty">Todavía no hay historial.</div>'}</div>`;qc('#foodHistoryModal').classList.add('show')}
function exportData(){const payload={exportedAt:new Date().toISOString(),profile:foodProfile,days:foodDays},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pirulin-comidas-${isoC()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),800)}
function wireComidas(){qc('#foodPrev').onclick=()=>{currentFoodDate=shiftDate(currentFoodDate,-1);renderComidas()};qc('#foodNext').onclick=()=>{currentFoodDate=shiftDate(currentFoodDate,1);renderComidas()};qc('#foodDate').onchange=e=>{currentFoodDate=e.target.value||isoC();renderComidas()};qc('#foodPasteFab').onclick=()=>qc('#foodPasteModal').classList.add('show');qc('#comidasMore').onclick=e=>{const m=qc('#comidasMenu'),r=e.currentTarget.getBoundingClientRect();m.style.left=`${Math.max(8,r.right-205)}px`;m.style.top=`${r.bottom+5}px`;m.classList.toggle('show')};document.addEventListener('pointerdown',e=>{if(!e.target.closest('#comidasMenu,#comidasMore'))qc('#comidasMenu')?.classList.remove('show')},true);document.addEventListener('click',e=>{const add=e.target.closest?.('[data-add]');if(add&&qc('#comidasSuite')?.classList.contains('show'))openModal(add.dataset.add);const f=e.target.closest?.('[data-edit-food]');if(f)openModal('food',currentDay().foods.find(x=>x.id===f.dataset.editFood));const s=e.target.closest?.('[data-edit-supp]');if(s)openModal('supplement',currentDay().supplements.find(x=>x.id===s.dataset.editSupp));const ex=e.target.closest?.('[data-edit-ex]');if(ex)openModal('exercise',currentDay().exercise.find(x=>x.id===ex.dataset.editEx));const cm=e.target.closest?.('#comidasMenu [data-cm]');if(cm){qc('#comidasMenu').classList.remove('show');if(cm.dataset.cm==='paste')qc('#foodPasteModal').classList.add('show');if(cm.dataset.cm==='profile')openProfile();if(cm.dataset.cm==='history')history();if(cm.dataset.cm==='export')exportData()}const close=e.target.closest?.('[data-close]');if(close)qc('#'+close.dataset.close)?.classList.remove('show');const hd=e.target.closest?.('[data-history-date]');if(hd){currentFoodDate=hd.dataset.historyDate;qc('#foodHistoryModal').classList.remove('show');renderComidas()}},true);qc('#foodModalSave').onclick=()=>saveModal().catch(e=>{console.error(e);sayC('No pude guardar')});qc('#foodPasteSave').onclick=()=>importPaste();qc('#foodProfileSave').onclick=()=>saveProfile().catch(console.error)}
function startComidas(){if(!window.PirulinComidas||!window.PirulinFirebase?.user||!installComidas())return false;currentFoodDate=currentFoodDate||isoC();stopFoodDays?.();stopFoodProfile?.();stopFoodDays=window.PirulinComidas.subscribeDays({onChange:d=>{foodDays=d;renderComidas()},onError:console.error});stopFoodProfile=window.PirulinComidas.subscribeProfile({onChange:p=>{foodProfile=p;renderComidas()},onError:console.error});renderComidas();return true}
function bootComidas(){if(startComidas())return;setTimeout(bootComidas,100)}
window.addEventListener('pirulin-auth-changed',e=>{if(e.detail?.signedIn)setTimeout(bootComidas,0);else{stopFoodDays?.();stopFoodProfile?.();stopFoodDays=stopFoodProfile=null;foodDays=[];foodProfile=null}});if(window.PirulinFirebase?.user)bootComidas();else setTimeout(bootComidas,100);
window.PirulinComidasLive={start:startComidas,get days(){return [...foodDays]},get profile(){return foodProfile}};
