let stopNotes=null,stopCategories=null;
let latestNotes=new Map(),latestCategories=new Map(),syncingCategories=false,examplesSeedAttempted=false;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
function safeEval(code,fallback=null){try{return window.eval(code)}catch(e){console.warn('Pirulín notes eval',e);return fallback}}
function say(msg){try{window.eval(`if(typeof say==='function')say(${JSON.stringify(msg)})`)}catch{console.log(msg)}}
function json(value){return JSON.stringify(value).replace(/</g,'\\u003c')}
function other(){return window.PirulinFirebase?.person==='Mateo'?'Dani':'Mateo'}
function emitRendered(){window.dispatchEvent(new CustomEvent('pirulin-notes-rendered'))}
function emitOpened(){window.dispatchEvent(new CustomEvent('pirulin-note-editor-opened'))}
function setMockNotes(notes){const data=notes.map(n=>({id:n.id,title:n.title||'Sin título',body:n.body||'',tags:Array.isArray(n.tags)?n.tags:[],shared:!!n.shared,pinned:!!n.pinned,drawing:n.drawing||'',createdBy:n.createdBy||null,createdByUid:n.createdByUid||null}));safeEval(`notesData=${json(data)};if(typeof renderNotes==='function')renderNotes();`);relabel();emitRendered()}
function setMockCategories(cats){const data=cats.map(c=>({id:String(c.id),name:String(c.name),parent:c.parent||null}));safeEval(`(()=>{const data=${json(data)};noteCategories.splice(0,noteCategories.length,...data);if(typeof selectedNoteFilters!=='undefined'){const valid=new Set(data.map(c=>c.id));[...selectedNoteFilters].forEach(id=>{if(!valid.has(id))selectedNoteFilters.delete(id)})}if(typeof renderNoteFilters==='function')renderNoteFilters();if(typeof renderNotes==='function')renderNotes();})()`);relabel();emitRendered()}
function relabel(){const target=other();qa('#notesGrid .note-card').forEach(card=>{const note=latestNotes.get(String(card.dataset.noteId)),chip=q('.note-chip',card);if(note?.shared&&chip)chip.textContent=`Con ${target}`});const label=q('#noteShareInput')?.closest('.note-pref')?.querySelector('span');if(label)label.textContent=`Compartir con ${target}`}
function openEditor(id=null){const ok=id?!!safeEval(`typeof openNoteEditor==='function'?(openNoteEditor(${JSON.stringify(String(id))}),true):false`,false):!!safeEval(`typeof openNoteEditor==='function'?(openNoteEditor(),true):false`,false);const modal=q('#noteModal');if(!ok||!modal){say('No pude abrir la nota');return false}modal.classList.remove('note-closing');modal.style.opacity='1';modal.classList.add('show');emitOpened();setTimeout(relabel,0);return true}
function readPayload(){window.PirulinNotesUI?.syncToTextarea?.();const title=q('#noteTitleInput')?.value?.trim()||'',body=q('#noteBodyInput')?.value?.trim()||'',drawing=safeEval('editingDrawing','')||'';if(!title&&!body&&!drawing)return null;const id=safeEval('editingNoteId',null),tags=safeEval('[...editingNoteTags]',[])||[],old=id?latestNotes.get(String(id)):null;return{id:String(id||`n${Date.now()}-${Math.random().toString(36).slice(2,6)}`),title:title||'Sin título',body,drawing,tags,shared:!!q('#noteShareInput')?.checked,pinned:!!q('#notePinInput')?.checked,createdBy:old?.createdBy||window.PirulinFirebase?.person||null,createdByUid:old?.createdByUid||window.PirulinFirebase?.user?.uid||null,previousShared:old?.shared??false}}
async function saveEditor(){const payload=readPayload();if(!payload){say('Escribí algo');return}try{const {previousShared,...note}=payload;await window.PirulinNotes.saveNote(note,{previousShared});window.PirulinNotesUI?.closeEditor?.();safeEval('editingNoteId=null;editingNoteTags=new Set();editingDrawing=""');say(note.shared?`Nota guardada y compartida con ${other()}`:'Nota guardada')}catch(e){console.error(e);say('No pude guardar la nota')}}
function menuButton(label,action,danger=false){return `<button data-note-action="${action}" style="width:100%;border:0;background:transparent;text-align:left;padding:10px 11px;border-radius:10px;font:800 13px Nunito,system-ui;color:${danger?'#d95762':'#343842'}">${label}</button>`}
function noteMenu(){let m=q('#pirulinNoteMenu');if(m)return m;m=document.createElement('div');m.id='pirulinNoteMenu';m.style.cssText='position:fixed;z-index:120;display:none;width:190px;padding:7px;background:#fff;border:1px solid #e8eaf0;border-radius:16px;box-shadow:0 16px 42px rgba(25,30,40,.18)';document.body.appendChild(m);return m}
function openMenu(card,button){const id=String(card?.dataset?.noteId||''),note=latestNotes.get(id);if(!note)return;const m=noteMenu();m.dataset.noteId=id;m.innerHTML=menuButton('Editar','edit')+menuButton(note.pinned?'Desfijar':'Fijar arriba','pin')+menuButton(note.shared?'Descompartir':`Compartir con ${other()}`,'share')+menuButton('Eliminar','delete',true);const r=button.getBoundingClientRect();m.style.left=`${Math.max(8,Math.min(innerWidth-198,r.right-190))}px`;m.style.top=`${Math.min(innerHeight-210,r.bottom+5)}px`;m.style.display='block'}
async function act(action,id){const note=latestNotes.get(String(id));if(!note)return;q('#pirulinNoteMenu').style.display='none';if(action==='edit'){openEditor(id);return}if(action==='delete'){if(!confirm(`¿Eliminar “${note.title}”?`))return;await window.PirulinNotes.deleteNote(note);return}if(action==='pin'){await window.PirulinNotes.saveNote({...note,pinned:!note.pinned},{previousShared:note.shared});return}if(action==='share'){await window.PirulinNotes.saveNote({...note,shared:!note.shared},{previousShared:note.shared});say(note.shared?'Nota descompartida':`Compartida con ${other()}`)}}
function headerMenu(){let m=q('#pirulinNotesHeaderMenu');if(m)return m;m=document.createElement('div');m.id='pirulinNotesHeaderMenu';m.style.cssText='position:fixed;z-index:120;display:none;width:190px;padding:7px;background:#fff;border:1px solid #e8eaf0;border-radius:16px;box-shadow:0 16px 42px rgba(25,30,40,.18)';m.innerHTML=menuButton('Categorías','categories')+menuButton('Exportar notas','export');document.body.appendChild(m);return m}
function exportNotes(){const payload={exportedAt:new Date().toISOString(),user:window.PirulinFirebase?.person||null,categories:[...latestCategories.values()],notes:[...latestNotes.values()]},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pirulin-notas-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function mockCats(){return safeEval('noteCategories.map(c=>({id:c.id,name:c.name,parent:c.parent||null}))',[])||[]}
async function syncCats(){if(syncingCategories)return;syncingCategories=true;try{const cur=new Map(mockCats().map(c=>[String(c.id),c])),ops=[];cur.forEach((c,id)=>{const old=latestCategories.get(id);if(!old||old.name!==c.name||(old.parent||null)!==(c.parent||null))ops.push(window.PirulinNotes.saveCategory(c))});latestCategories.forEach((_,id)=>{if(!cur.has(id))ops.push(window.PirulinNotes.deleteCategory(id))});await Promise.all(ops)}finally{syncingCategories=false}}
function hooks(){if(document.documentElement.dataset.notesLiveV3)return;document.documentElement.dataset.notesLiveV3='1';noteMenu();headerMenu();document.addEventListener('click',e=>{const add=e.target.closest?.('#addNoteBtn');if(add){e.preventDefault();e.stopImmediatePropagation();openEditor();return}const more=e.target.closest?.('.note-more');if(more){e.preventDefault();e.stopImmediatePropagation();openMenu(more.closest('.note-card'),more);return}const card=e.target.closest?.('#notesGrid .note-card');if(card&&!e.target.closest?.('button,a,input')){e.preventDefault();e.stopImmediatePropagation();openEditor(card.dataset.noteId);return}if(e.target.closest?.('#saveNoteBtn')){e.preventDefault();e.stopImmediatePropagation();saveEditor();return}const action=e.target.closest?.('#pirulinNoteMenu [data-note-action]');if(action){e.preventDefault();e.stopImmediatePropagation();act(action.dataset.noteAction,q('#pirulinNoteMenu').dataset.noteId).catch(console.error);return}const head=e.target.closest?.('#notesMore');if(head){e.preventDefault();e.stopImmediatePropagation();const m=headerMenu(),r=head.getBoundingClientRect();m.style.left=`${Math.max(8,r.right-190)}px`;m.style.top=`${r.bottom+6}px`;m.style.display=m.style.display==='block'?'none':'block';return}const ha=e.target.closest?.('#pirulinNotesHeaderMenu [data-note-action]');if(ha){e.preventDefault();e.stopImmediatePropagation();q('#pirulinNotesHeaderMenu').style.display='none';if(ha.dataset.noteAction==='categories')safeEval('openCategoryEditor()');else exportNotes();return}if(e.target.closest?.('#categoryEditorModal,#createCategoryFromNote,#openCategoryEditor'))setTimeout(syncCats,100)},true)}
async function seedExamples(){if(examplesSeedAttempted||!window.PirulinNotes?.seedExampleNotesOnce)return;examplesSeedAttempted=true;try{await window.PirulinNotes.seedExampleNotesOnce()}catch(e){console.warn('Pirulín examples',e)}}
function start(){if(!window.PirulinNotes||!window.PirulinFirebase?.user||!q('#notesGrid'))return false;stopNotes?.();stopCategories?.();stopNotes=window.PirulinNotes.subscribeNotes({onChange:notes=>{latestNotes=new Map(notes.map(n=>[String(n.id),n]));setMockNotes(notes)},onError:e=>console.error(e)});stopCategories=window.PirulinNotes.subscribeCategories({onChange:cats=>{latestCategories=new Map(cats.map(c=>[String(c.id),c]));setMockCategories(cats)},onError:e=>console.error(e)});hooks();seedExamples();return true}
function boot(){if(start())return;setTimeout(boot,100)}
window.addEventListener('pirulin-auth-changed',e=>{if(e.detail?.signedIn)setTimeout(boot,0);else{stopNotes?.();stopCategories?.();stopNotes=stopCategories=null;latestNotes.clear();latestCategories.clear();examplesSeedAttempted=false}});if(window.PirulinFirebase?.user)boot();else setTimeout(boot,100);window.PirulinNotesLive={start,get notes(){return [...latestNotes.values()]},get categories(){return [...latestCategories.values()]}};
