const $n=(s,r=document)=>r.querySelector(s),$$n=(s,r=document)=>[...r.querySelectorAll(s)];
const PALETTES=[['#fff8c9','#f4e9a7'],['#f9e5ea','#efd1da'],['#e8f5df','#d5e9c9'],['#e6f0fb','#d3e3f4'],['#eee7fa','#ddd2f1'],['#fdebd8','#f4dac0']];
let savedRange=null;
function hash(v=''){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function esc(t=''){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function sanitize(html=''){const tpl=document.createElement('template');tpl.innerHTML=String(html);const allowed=new Set(['DIV','P','SPAN','STRONG','B','EM','I','U','H3','UL','OL','LI','A','BR','INPUT']);const walk=n=>{[...n.childNodes].forEach(c=>{if(c.nodeType!==1)return;if(!allowed.has(c.tagName)){c.replaceWith(...c.childNodes);return}[...c.attributes].forEach(a=>{const keep=(c.tagName==='A'&&['href','target','rel'].includes(a.name))||(c.tagName==='INPUT'&&['type','checked'].includes(a.name))||(['DIV','P','SPAN'].includes(c.tagName)&&['class','contenteditable'].includes(a.name));if(!keep)c.removeAttribute(a.name)});if(c.tagName==='A'){const href=c.getAttribute('href')||'';if(!/^https?:\/\//i.test(href))c.removeAttribute('href');c.target='_blank';c.rel='noopener'}if(c.tagName==='INPUT'){c.type='checkbox';if(!c.closest('.note-todo'))c.remove()}walk(c)})};walk(tpl.content);return tpl.innerHTML}
function toHtml(text=''){if(!text)return '';if(/<\/?(?:strong|b|em|i|u|h3|ul|ol|li|a|div|p|span|input|br)\b/i.test(text))return sanitize(text);const inline=s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');let out='',list=false;for(const line of String(text).split(/\r?\n/)){const todo=line.match(/^\s*-\s*\[([ xX])\]\s*(.*)$/);if(todo){if(list){out+='</ul>';list=false}out+=`<div class="note-todo"><input type="checkbox" ${todo[1].toLowerCase()==='x'?'checked':''}><span contenteditable="true">${inline(todo[2])}</span></div>`;continue}const li=line.match(/^\s*-\s+(.+)$/);if(li){if(!list){out+='<ul>';list=true}out+=`<li>${inline(li[1])}</li>`;continue}if(list){out+='</ul>';list=false}const h=line.match(/^###\s+(.+)$/);out+=h?`<h3>${inline(h[1])}</h3>`:(line?`<div>${inline(line)}</div>`:'<div><br></div>')}if(list)out+='</ul>';return out}
function styles(){if($n('#notesV3Styles'))return;const s=document.createElement('style');s.id='notesV3Styles';s.textContent=`
#notesSuite,#notesSuite *{-webkit-tap-highlight-color:transparent}
#notesSuite .header h1{font-size:27px!important}#notesSuite .notes-search input{font-size:15px!important}#notesSuite .notes-filter-chip{font-size:12px!important}
#notesSuite .note-card{border-radius:10px!important;min-height:162px!important;padding:0 14px 13px!important;gap:9px!important;background:var(--note-bg,#fff8c9)!important;border:1px solid rgba(66,60,45,.1)!important;box-shadow:0 5px 14px rgba(28,39,73,.055)!important;overflow:hidden;user-select:none;touch-action:manipulation}
#notesSuite .note-title{margin:0 -14px 2px!important;padding:12px 14px 11px!important;background:var(--note-head,#f4e9a7)!important;font-size:18px!important;font-weight:900!important;color:#29303a!important}
#notesSuite .note-preview{font-size:14px!important;line-height:1.44!important;color:#505968!important}#notesSuite .note-tag,#notesSuite .note-chip{font-size:10.5px!important}
#noteModal{opacity:1!important}#noteModal.show{opacity:1!important}#noteModal.show .notes-sheet{animation:noteSheetIn .22s cubic-bezier(.2,.9,.2,1) both}#noteModal.note-closing{display:flex!important;opacity:1!important;pointer-events:none}#noteModal.note-closing .notes-sheet{animation:noteSheetOut .16s ease-in both}
@keyframes noteSheetIn{from{opacity:.35;transform:translateY(24px) scale(.985)}to{opacity:1;transform:none}}@keyframes noteSheetOut{from{opacity:1;transform:none}to{opacity:.2;transform:translateY(22px) scale(.99)}}
#noteModal .note-editor-toolbar{display:grid!important;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px!important;overflow:visible!important;margin:10px 0 6px!important;padding:0!important;width:100%}
#noteModal .note-editor-tool{min-width:0!important;width:100%!important;height:40px!important;padding:0!important;border-radius:11px!important;display:grid!important;place-items:center!important;background:#f0f2f6!important;color:#5c667a!important;border:1px solid transparent!important;font-size:17px!important;font-weight:900!important;line-height:1!important;box-shadow:none!important;overflow:hidden!important;white-space:nowrap!important}
#noteModal .note-editor-tool:hover{background:#e9ecf2!important}#noteModal .note-editor-tool.is-active{background:#ded4f6!important;color:#6544b2!important;border-color:#cbbaf0!important;box-shadow:inset 0 0 0 1px rgba(101,68,178,.08)!important}
#noteBodyInput{display:none!important}#noteRichEditor{min-height:225px;max-height:340px;overflow:auto;border:1px solid #e1e5ec;background:#fffdf5;color:#30353e;font:600 17px/1.5 Nunito,system-ui,sans-serif;padding:58px 14px 18px;outline:none;overflow-wrap:anywhere;-webkit-user-select:text;user-select:text;caret-color:#5f48ac}
#noteRichEditor:empty:before{content:'Escribí lo que quieras…';color:#9aa1ad}#noteRichEditor h3{font-size:21px;margin:8px 0}#noteRichEditor .note-todo{display:flex;gap:9px;margin:7px 0}#noteRichEditor .note-todo input{width:20px;height:20px;accent-color:#8660de}#noteRichEditor .note-todo input:checked+span{text-decoration:line-through;color:#8b929c}`;document.head.appendChild(s)}
function editor(){const ta=$n('#noteBodyInput');if(!ta)return null;let e=$n('#noteRichEditor');if(e)return e;e=document.createElement('div');e.id='noteRichEditor';e.contentEditable='true';e.spellcheck=true;ta.insertAdjacentElement('afterend',e);const sync=()=>ta.value=sanitize(e.innerHTML).trim();e.addEventListener('input',()=>{sync();updateToolbarState()});e.addEventListener('click',ev=>{if(ev.target.matches('input[type="checkbox"]'))setTimeout(sync,0);setTimeout(updateToolbarState,0)});return e}
function syncFromTextarea(){const ta=$n('#noteBodyInput'),e=editor();if(ta&&e){const h=toHtml(ta.value||'');if(e.innerHTML!==h)e.innerHTML=h;updateToolbarState()}}
function syncToTextarea(){const ta=$n('#noteBodyInput'),e=$n('#noteRichEditor');if(ta&&e)ta.value=sanitize(e.innerHTML).trim()}
function remember(){const e=$n('#noteRichEditor'),s=window.getSelection();if(!e||!s||!s.rangeCount)return;const r=s.getRangeAt(0);if(e.contains(r.commonAncestorContainer))savedRange=r.cloneRange();updateToolbarState()}
function restore(){const e=$n('#noteRichEditor'),s=window.getSelection();if(!e||!s)return;e.focus();if(savedRange){try{s.removeAllRanges();s.addRange(savedRange)}catch{}}}
function selectionElement(){const e=$n('#noteRichEditor'),s=window.getSelection();if(!e||!s||!s.rangeCount)return null;let n=s.anchorNode;if(!n)return null;if(n.nodeType===3)n=n.parentElement;return e.contains(n)?n:null}
function updateToolbarState(){const t=$n('#noteModal .note-editor-toolbar');if(!t)return;const set=(sel,on)=>$n(sel,t)?.classList.toggle('is-active',!!on);let bold=false,italic=false,underline=false,list=false;try{bold=document.queryCommandState('bold');italic=document.queryCommandState('italic');underline=document.queryCommandState('underline');list=document.queryCommandState('insertUnorderedList')}catch{}const el=selectionElement();set('[data-note-format="bold"]',bold);set('[data-note-format="italic"]',italic);set('[data-note-format="underline"]',underline);set('[data-note-format="list"]',list||!!el?.closest('ul'));set('[data-note-format="todo"]',!!el?.closest('.note-todo'));set('[data-note-format="link"]',!!el?.closest('a'))}
function cmd(c,v=null){restore();document.execCommand(c,false,v);remember();syncToTextarea();updateToolbarState()}
function prepButton(btn,label,format,title){if(!btn)return;btn.type='button';btn.textContent=label;btn.dataset.noteFormat=format;btn.title=title;btn.onmousedown=e=>e.preventDefault()}
function toolbar(){const t=$n('#noteModal .note-editor-toolbar');if(!t||t.dataset.v4)return;t.dataset.v4='1';const b=$n('[data-wrap="**"]',t),i=$n('[data-wrap="*"]',t),u=$n('[data-prefix="### "]',t),l=$n('[data-prefix="- "]',t),link=$n('[data-link-tool]',t),draw=$n('#openDrawingBtn',t);prepButton(b,'B','bold','Negrita');prepButton(i,'I','italic','Cursiva');prepButton(u,'U','underline','Subrayado');prepButton(l,'•','list','Lista con viñetas');prepButton(link,'↗','link','Agregar link');prepButton(draw,'✎','draw','Dibujar');if(b)b.onclick=e=>{e.preventDefault();cmd('bold')};if(i)i.onclick=e=>{e.preventDefault();cmd('italic')};if(u)u.onclick=e=>{e.preventDefault();cmd('underline')};if(l)l.onclick=e=>{e.preventDefault();cmd('insertUnorderedList')};let todo=$n('[data-note-format="todo"]',t);if(!todo){todo=document.createElement('button');todo.className='note-editor-tool';prepButton(todo,'☑','todo','Lista de tareas');t.insertBefore(todo,link||null)}todo.onclick=e=>{e.preventDefault();restore();document.execCommand('insertHTML',false,'<div class="note-todo"><input type="checkbox"><span contenteditable="true">Tarea</span></div><div><br></div>');syncToTextarea();remember();updateToolbarState()};const ed=editor();ed?.addEventListener('mouseup',remember);ed?.addEventListener('keyup',remember);ed?.addEventListener('touchend',()=>setTimeout(remember,0));document.addEventListener('selectionchange',()=>{if($n('#noteModal')?.classList.contains('show'))updateToolbarState()});if(link)link.onclick=e=>{e.preventDefault();remember();const label=$n('#noteLinkLabel'),url=$n('#noteLinkUrl');if(label)label.value=window.getSelection()?.toString()||'';if(url)url.value='';$n('#noteLinkEditor')?.classList.add('show')};const apply=$n('#applyNoteLink');if(apply)apply.onclick=e=>{e.preventDefault();const raw=$n('#noteLinkUrl')?.value.trim()||'';if(!raw)return;const url=/^[a-z]+:\/\//i.test(raw)?raw:'https://'+raw,label=$n('#noteLinkLabel')?.value.trim()||url;restore();const s=window.getSelection();if(s&&s.rangeCount&&s.toString())document.execCommand('createLink',false,url);else document.execCommand('insertHTML',false,`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}</a>`);$n('#noteLinkEditor')?.classList.remove('show');syncToTextarea();remember();updateToolbarState()};updateToolbarState()}
function paint(){const notes=window.PirulinNotesLive?.notes||[];$$n('#notesGrid .note-card').forEach(c=>{const id=String(c.dataset.noteId||''),p=PALETTES[hash(id)%PALETTES.length];c.style.setProperty('--note-bg',p[0]);c.style.setProperty('--note-head',p[1]);const n=notes.find(x=>String(x.id)===id),pr=$n('.note-preview',c);if(n&&pr){const h=toHtml(n.body||'');if(pr.innerHTML!==h)pr.innerHTML=h}})}
function closeEditor(){const m=$n('#noteModal');if(!m||!m.classList.contains('show'))return;m.classList.add('note-closing');setTimeout(()=>{m.classList.remove('show','note-closing');m.style.opacity=''},165)}
function prepareOpen(){const m=$n('#noteModal');if(!m)return;m.classList.remove('note-closing');m.style.opacity='1';m.classList.add('show');requestAnimationFrame(()=>{syncFromTextarea();$n('#noteTitleInput')?.focus({preventScroll:true});updateToolbarState()})}
function install(){if(document.documentElement.dataset.notesUiV4)return;document.documentElement.dataset.notesUiV4='1';styles();editor();toolbar();paint();window.addEventListener('pirulin-notes-rendered',paint);window.addEventListener('pirulin-note-editor-opened',prepareOpen);document.addEventListener('click',e=>{if(e.target.closest?.('#saveNoteBtn'))syncToTextarea();if(e.target.closest?.('#cancelNoteBtn')){e.preventDefault();e.stopImmediatePropagation();closeEditor()}if(e.target.id==='noteModal'){e.preventDefault();e.stopImmediatePropagation();closeEditor()}},true)}
function boot(){if(!$n('#noteModal')||!$n('#notesGrid'))return setTimeout(boot,80);install()}
boot();window.PirulinNotesUI={paint,prepareOpen,closeEditor,syncFromTextarea,syncToTextarea,updateToolbarState};
