const CACHE = 'pirulin-pwa-v0.11.10-dev';
const CORE = [
  './','./index.html','./mockup_pirulin_v51.html','./firebase-client.js',
  './tasks-repository.js','./tasks-preferences.js','./tasks-advanced.js','./tasks-live-adapter.js',
  './notes-repository.js','./notes-ui-v3.js','./notes-editor-fixes.js','./notes-live-v3.js','./notes-colors.js','./notes-keep-polish.js','./notes-menu-dismiss.js',
  './expenses-repository.js','./expenses-live.js','./expenses-final-fixes.js','./expenses-settle-celebration.js','./expenses-ui-polish.js','./expenses-percent-slider.js','./expenses-migration.js','./expenses-categories.js','./expenses-card-compact.js','./expenses-report.js','./expenses-report-motion.js',
  './subapp-transitions.js','./pirulin-icon.svg','./manifest.webmanifest','./icon.svg','./icon-maskable.svg'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)));self.skipWaiting()});self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))));self.clients.claim()});
function isCritical(url,request){if(request.mode==='navigate')return true;return /\/(?:index\.html|mockup_pirulin_v51\.html|firebase-client\.js|tasks-repository\.js|tasks-preferences\.js|tasks-advanced\.js|tasks-live-adapter\.js|notes-repository\.js|notes-ui-v3\.js|notes-editor-fixes\.js|notes-live-v3\.js|notes-colors\.js|notes-keep-polish\.js|notes-menu-dismiss\.js|expenses-repository\.js|expenses-live\.js|expenses-final-fixes\.js|expenses-settle-celebration\.js|expenses-ui-polish\.js|expenses-percent-slider\.js|expenses-migration\.js|expenses-categories\.js|expenses-card-compact\.js|expenses-report\.js|expenses-report-motion\.js|subapp-transitions\.js|pirulin-icon\.svg)$/.test(url.pathname)}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin){event.respondWith(fetch(event.request).catch(()=>caches.match(event.request)));return}if(isCritical(url,event.request)){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>caches.match(event.request).then(cached=>cached||caches.match('./index.html'))));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}))) });
